### PR TITLE
Included new command (DST) for Dallas temperature sensors DS18B20

### PR DESCRIPTION
**Pull request by ronaldsteen**
Hi,

I've included a new command that let's you read a Dalles DS18B20 temp sensor on digital pin 2.
I've also added this command to homeduino and homeduinojs so it's usable in Pimatic.

Let me know what you think. Would be great if it could be included in the official packages.

Cheers,
Ronald

### CODE REVIEW

**Comment by sweetpi** [comment]
Nice, I will correct the DST device. I think there are no checksum errors and stuff, right?

**Comment by sweetpi** [comment]
I've done some cleanup, could you test if its working? Then I will release a new version.

**Comment by ronaldsteen** [comment]
Nice. I'll try testing it on monday or tuesday evening.

**Comment by ronaldsteen** [comment]
I see you've removed the lines below. Are those attribures already inherited from TemperatureSensor?
If not, I guess they're kinda required.

```javascript
    attributes:
      temperature:
        description: "the messured temperature"
        type: "number"
        unit: '°C'
```

**Comment by sweetpi** [comment]
> I see you've removed the lines below from homeduino.coffee . Are those attribures already inherited from TemperatureSensor?
> If not, I guess they're kinda required.

Yes those are.

**Comment by ronaldsteen** [comment]
Still had some time to test it tonight. All is working fine.

**Pull request merged**
