### PR TITLE
Updated configurability

### PR DESCRIPTION
**Pull request by ronaldsteen**
Hi, 

I've updated configurability. You can now specify pins and addresses.

Cheers,
Ronald

### CODE REVIEW

**Comment by frosenheimer** [comment]
I`m just testing your versions of homeduino and pimatic-homeduino. It seems to miss an action called readDstSensors, which is called at the beginning of homeduino.coffee.

error [pimatic-homeduino]: Couldn't connect to homeduino device: Object #<Board> has no method 'readDstSensors'.

**Comment by ronaldsteen** [comment]
It requires the adjusted version of homeduinojs too. By default you get the current version of that package. You can replace it by manually cloning my homeduinojs version in your node_modules folder.

Let me know if you need more detailed instructions for testing it.

**Comment by frosenheimer** [comment]
Sorry, seems that it did not copy homeduninojs. Now it is working.
Although there seems to be a wrong type of the temperature variable.

in homeduino.coffee:
    attributes:
      temperature:
        description: "the meassured temperature"    
        type: "string"    
        unit: '°C'
        pin: "number"
        address: "string"

I think it should be:
    attributes:
      temperature:
        description: "the meassured temperature"    
        type: "number"   <---- has to be number  
        unit: '°C'
        pin: "number"
        address: "string"

**Comment by ronaldsteen** [comment]
Thanks. I've just updated it.

**Comment by sweetpi** [comment]
I've remote the pin and address attribute, because I think it does not make much sense to have this as an attribute visible in the gui.

Thanks again for the additions.

**Comment by ronaldsteen** [comment]
Ok, I think you're right.

**Comment by frosenheimer** [comment]
Could it be that you deleted the temperature attribute with the pin and the address attribute? Or am I blind :(

**Comment by ronaldsteen** [comment]
I thought the format was wrong.. pin and address were part of temperature, now they're separate attributes. 
    
```
attributes:
      temperature:
        description: "the meassured temperature"    
        type: "number"    
        unit: '°C'
      pin:
        description: "The pin that the sensor is connected to."
        type: "number"
      address:
        description: "The address of the sensor."
        type: "string"
```

**Comment by sweetpi** [comment]
> Could it be that you deleted the temperature attribute with the pin and the address attribute? Or am I blind :(

I delete all, because the temperature attribute gets inherit from TemperatureSensor anyway.

**Comment by frosenheimer** [comment]
thanks for your explanation. I`m just getting the hang of the programming for ardunio and pimatic (coffee)

**Pull request merged**
