### PR TITLE
add rollingTime to support moving by percentage

### PR DESCRIPTION
**Pull request by michbeck100**
This change is analogous to the changes made in https://github.com/pimatic/pimatic/pull/920 for the DummyShutter

### CODE REVIEW

**Comment by 0rTiN** [comment]
Please bring this in the next version.

**Comment by mwittig** [comment]
Sure. Will do among other thing required for homeduino like Migration to
new Serialport implementation and integration of the the new build for
virtual homeduino

2017-12-20 19:35 GMT+01:00 0rTiN <notifications@github.com>:

**Comment by 0rTiN** [comment]
Wonderfull. Will this come soon or does it need longer time to release the new functions?

**Comment by mwittig** [comment]
Well someone needs to test the feature

**Comment by 0rTiN** [comment]
I can do it.

**Comment by 0rTiN** [comment]
I tried to replace the relevant files, but pimatic was not starting anymore. How can I make it running for a test?

**Comment by michbeck100** [comment]
Like this: https://stackoverflow.com/questions/6022302/how-to-apply-unmerged-upstream-pull-requests-from-other-forks-into-my-fork and then install the plugin from github

**Comment by michbeck100** [comment]
Will this be in the next release, too?

**Comment by theslash** [comment]
Is this already implemented? Can I do something to help?

**Comment by michbeck100** [comment]
@theslash you could test if the rolling time works for you.

**Comment by theslash** [comment]
Ok, so I set a rolling time for one of my shutters of 23 seconds.
When I then call the moveByPercentage like this:
curl -X GET "http://192.168.1.5:8080/api/device/rollo-esszimmer/moveByPercentage?percentage=-10"
the shutter moves down approx 10% and so on, when I use positive numbers, then it moves up.
So this is good I think.

**Pull request merged**
